### ISSUE TITLE
I really do want to love blackarch and its the best ive got right now but HELP ME

### ISSUE THREAD

**Issue by HackMeDevanSugars** [BlackArch/blackarch-site#101]
This is my first ever attempt to switch to another OS so the first time I installed BlackArch I got it working in a week and figured out nothing was working because I didn't install it well then I decided to try to install it and it broke so got a clean install and installation broke again im now 2 months in and no further than I was a month ago and now my usb 3.0 port is broken and i tried just installing it to my c drive and it told me bundlr.mrb or something of the sort was damaged or missing and i got close to finishing with one of them and my 3rd sda I had made wasnt showing up and of course installation instructions are out of date im guessing cause I followed them exactly every time

**Comment by ikstream** [comment]
So what's your current state?
How can we help you?
Did you use the live iso?
Was your "3rd sda" on the same physical drive as the other?

**Comment by HackMeDevanSugars** [comment]
> So what's your current state?
> How can we help you?
> Did you use the live iso?
> Was your "3rd sda" on the same physical drive as the other?

so being that my usb 3.0 turned out to be broken and it was the only one that actually ever appeared in bios i tried using unetbootin to replace my c drive and i was missing bundlr.mdr so i tried downloading the iso again and im about to try it again and i want to install blackarch on to the system to be my main system i did use the live iso i want to know why sda 3 was missing because thats when i got the furthest and then ill let you guys know once i get it connected to the internet on the blackarch os or if it didnt work

**Comment by noptrix** [comment]
thanks @HackMeDevanSugars

**Comment by HackMeDevanSugars** [comment]
> thanks @HackMeDevanSugars

for?

**Comment by noptrix** [comment]
lol, for letting us know... ;)

**Comment by HackMeDevanSugars** [comment]
your welcome lol after i redownloaded the iso i just went to bed so i just woke up

**Comment by HackMeDevanSugars** [comment]
welp bundlr.mdr was missing again and im thinking about just screwing blackarch and using something similar is there any other os close to blackarch

**Comment by ikstream** [comment]
> welp bundlr.mdr was missing again and im thinking about just screwing blackarch and using something similar is there any other os close to blackarch

Did you check if the checksum of the iso file matches the one on the website?
Another option would be to install an arch linux distro (Arch linux/manjaro/antergos) first and install the blackarch repo on top of it.

[EDIT]
What do you mean by missing bundlr.mdr?

**Comment by ikstream** [comment]
As there is no additional input i am closing this issue
