### ISSUE TITLE
strap.h and partial upgrade

### ISSUE THREAD

**Issue by ghost** [BlackArch/blackarch-site#103]
Hello !

I just discovered blackarch and being currently trying to level up my understanding of scripts and the linux functionning I was looking at the installation script "strap.h" trying to understand it, and there is one thing i didn't catch, so I wanted to ask.
- why is "pacman_upgrade" not used in the script?
- and so with "pacman_update" called at the end, without doing an upgrade right after, is there not a risk of partial upgrade (https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported) ?

Thanks !

**Comment by ikstream** [comment]
There is no partial update in the script. During a partial update you update a single (or multiple) packages as mentioned in your link. `pacman -Syy` just force refreshes the package database.
Have a look at the man page of pacman for additional information.
Currently we just leave the sysupgrade to the user. 

Best regards
