### ISSUE TITLE
Blackarch Tools issue

### ISSUE THREAD

**Issue by DharmeshDcruz** [BlackArch/blackarch-site#115]
when i click blackarch linux tools .it is not opening or launching .when i type tool name in terminal it opens .how to solve that .i need opening tools by clicking it. please someone help .and some tools is not opening also i type in terminal.

**Comment by ikstream** [comment]
Can you please provide some more information?

Which tools, which DE are you using etc.

**Comment by DharmeshDcruz** [comment]
even all tools not opening or pop in blackarch menu. like the image you have seen.it shows tools but when i am click that . it is not opening. please help me.
![640px-Blackarch-menu](https://user-images.githubusercontent.com/57396751/68314703-85f5a800-00ae-11ea-99af-f8c7b7e1c340.png)

**Comment by ikstream** [comment]
What desktop environment are you using?
Have you checked the logs the DE?
Which tool is not opening in terminal?

**Comment by DharmeshDcruz** [comment]
how to find DE.
all tools is opening in terminal .but tools is not opening in blackarch menu.
Please Help Me.

**Comment by Dharmesh-Dez** [comment]
Tools have been updated

**Comment by DharmeshDcruz** [comment]
yes i am updated. but not opening

**Comment by noptrix** [comment]
@DharmeshDcruz this is due to urxvt (xterminal). we will fix this along the next ISO/OVA release. ETA: end of Dec

**Comment by aancw** [comment]
I think this is not related to blackarch-site repo. Closed. Feel free to reopen.
