### ISSUE TITLE
 I can't connect to wifi after installing from live usb

### ISSUE THREAD

**Issue by Thatguy32123** [BlackArch/blackarch-site#119]
I can't connect to my wifi after installing blackarch from a live usb, also wicd was replaced with wifi-radar

**Comment by ikstream** [comment]
Are there any error messages? What have you tried? Do you even have a wifi adapter?

**Comment by noraj** [comment]
This repo is the website source, I think https://github.com/BlackArch/blackarch-installer would be more appropriate.

**Comment by aancw** [comment]
Please always show us an error message and upload log of your system for better recommendation. We can't guessing blindly.
