### ISSUE TITLE
Issues connecting to repository mirror.

### ISSUE THREAD

**Issue by t0ta1packag3** [BlackArch/blackarch-site#120]
When I run `sudo pacman -Syyu` to update Arch, I get the following error:

`:: Synchronizing package databases...
 core                  134.0 KiB   220 KiB/s 00:01 [##########################] 100%
 extra                1701.6 KiB   997 KiB/s 00:02 [##########################] 100%
 community               4.9 MiB  2.39 MiB/s 00:02 [##########################] 100%
error: failed retrieving file 'blackarch.db' from www.mirrorservice.org : The requested URL returned error: 503
error: failed to update blackarch (failed to retrieve some files)
error: failed to synchronize all databases`

A quick search shows 503 errors are usually an issue on the server side, not the client side. Is there an issue with the server at www.mirrorservice.org, and if not, what are some possible solutions to sync with the repositories?

**Comment by noraj** [comment]
This repository is about the website blackarch.org so this issue doesn't belong here.

How ever you just have an issue with one mirror, just comment this one and pick another one in `/etc/pacman.d/blackarch-mirrorlist`.
