### ISSUE TITLE
Unrecognized archive format - updating DB

### ISSUE THREAD

**Issue by PiratePenguinZA** [BlackArch/blackarch-site#141]
Good day, 

I installed BlackArch slim yesterday as my Pentest OS, but I'm getting the below error when ever I try to install additional packages or update the existing ones.

error: could not open file /var/lib/pacman/sync/core.db: Unrecognized archive format
error: could not open file /var/lib/pacman/sync/extra.db: Unrecognized archive format
error: could not open file /var/lib/pacman/sync/community.db: Unrecognized archive format
error: could not open file /var/lib/pacman/sync/multilib.db: Unrecognized archive format

I think what was formally the top site on the mirror list (evowave) got bought out and now mirrors.evowave.com redirects to Zerobounce.com I see on the Arch Linux wiki  it is recommended to log in as Root & than delete the corrupted DB as well update the mirror list & download the latest files, but  I'm unable to access the Superuser account ( This account is currently not available)

Your urgent assistance would be greatly appreciated, Thank you

**Comment by ikstream** [comment]
See BlackArch/blackarch#3183 for a solution
