### ISSUE TITLE
Installing on top of Archlinux "you don't have an internet conection" error

### ISSUE THREAD

**Issue by Ezteb** [BlackArch/blackarch-site#153]
Folowing the instructions for **Installing on top of ArchLinux** on **https://blackarch.org/downloads.html**

The **strap.sh** script downloaded stops whit error **you don't have an internet conection**

Inspecting the script found that the internet cheking is due to a curl call to **https://example.com** in the 50th line

Said page is down now so changing it to a working page fix the issue

Maybe change that to a needed url for the project as **https://blackarch.org** or **https://archlinux.org** can be a permanent solution?

**Comment by noraj** [comment]
It's weird but not the first time. In the past we used microsoft.com but changed for example.com https://github.com/BlackArch/blackarch-site/commit/ebf38ca794344c866d58c4b8f7f6af050de975d3. Yet the issue happens sometimes https://github.com/BlackArch/blackarch-site/issues/150. Maybe we should change to something more stable.

**Comment by YonLiud** [comment]
I have created a [PR](https://github.com/BlackArch/blackarch-site/pull/159) with a fix

You (@noraj) said in #150 :
> it's a good source.

It's not. never when I tried to install the BlackArch repository and it always showed me an internet error causing me to remove `check_internet` from the file completely. 

The only quick fix I have found is: 
```diff
[Line 188]
- check_internet
```

**Comment by Ezteb** [comment]
Maybe can be solved checking response for the repositories.
Because if the repo is down you can't install anyway insted of using a third party that is not related to this project and out of control and relevancy for the action of installing??

**Comment by noraj** [comment]
@YonLiud maybe example.com is blocked in some region of the world

**Comment by YonLiud** [comment]
> @YonLiud maybe example.com is blocked in some region of the world

does not change the fact it's unreliable and is probably not the best choice to use in international versions of the script

**Comment by YonLiud** [comment]
> Maybe can be solved checking response for the repositories. Because if the repo is down you can't install anyway insted of using a third party that is not related to this project and out of control and relevancy for the action of installing??

@Ezteb 
I did think of that but I believe that a more simple approach is just to check if ``blackarch.org`` is up since the repo is on it

**Comment by Ezteb** [comment]
oh ok then that is the best solution i can see at the moment.

my reference to the repo response is because can try multiple mirrors and if one is up the installation can continue.

that aproach problem is from where obtain the mirros list which drops again to the project webpage so changing example.com to blackarch.org maybe the most stable solution been that page vital for the installation.

**Comment by Ezteb** [comment]
thanks for the time and patience!!
sorry for the duplicate I am native spanish speaker so generally search issues and errors tru copy/paste error messages never mentioned in #150
