### ISSUE TITLE
Wrong checksum for strap.sh

### ISSUE THREAD

**Issue by aeselev-acti** [BlackArch/blackarch-site#160]
### Bug description

Wrong checksum for strap.sh

### Steps to reproduce

curl https://blackarch.org/checksums/strap 
curl https://blackarch.org/strap.sh | sha1sum

**Actual result:** 
6424ecf8d2e376c42b0db7fd38c87a8d2f32a7b5  strap.sh
5ea40d49ecd14c2e024deecf90605426db97ea0c  strap.sh

**Expected result:**
5ea40d49ecd14c2e024deecf90605426db97ea0c  strap.sh
5ea40d49ecd14c2e024deecf90605426db97ea0c  strap.sh

**Comment by aeselev-acti** [comment]
So, BlackArch installation fails with error on strap.sh checksum

**Comment by noraj** [comment]
```
$ sha1sum strap 
bc098b31ec823d8698272c38a995296c6bd9b5c5  strap
$ sha1sum strap.sh 
5ea40d49ecd14c2e024deecf90605426db97ea0c  strap.sh
```

it seems the correct hash was set in ea9804b69e3eacf88d8cf22c21aa37de3129d793 to reflect this change https://github.com/BlackArch/blackarch-site/pull/159
but I don't know why it was changed one day after 84abf5ad4ba0c438398c68de940617a33148dea4, is that a mistake @noptrix?
