### ISSUE TITLE
All Torrent links on homepage return 404

### ISSUE THREAD

**Issue by YonLiud** [BlackArch/blackarch-site#171]
All torrent links on the homepage are returning a 404 error. This issue is currently affecting three links, which are:

- `https://blackarch.org/blackarch/torrent/blackarch-linux-full-2023.04.01-x86_64.iso.torrent`
- `https://blackarch.org/blackarch/torrent/blackarch-linux-slim-2023.04.01-x86_64.iso.torrent`
- `https://blackarch.org/blackarch/torrent/blackarch-linux-netinst-2023.04.01-x86_64.iso.torrent`

These links were previously working, but they are no longer functional. I have tested the links multiple times and have confirmed that they are indeed returning a 404 error.

#### Steps to reproduce:
1. Visit the homepage.
2. Click on any of the three torrent links mentioned above.
3. Observe that the link returns a 404 error.

#### Expected behavior:
The links should lead to a valid torrent file download.

#### Actual behavior:
All three links lead to a 404 error page.

#### Additional Information:
It's worth noting that the other download methods (e.g., direct download) seem to be working properly. Therefore, I suspect that the issue might be related to the torrent files themselves being missing or not properly uploaded to the website's CDN.

**Comment by esselfe** [comment]
Also the mirrors only have the 2021 version of the torrents, not the expected 2023-04.

**Comment by noraj** [comment]
@noptrix @ikstream Do you know what the issue is with the torrent files?

**Comment by noraj** [comment]
Waiting for the update on blackarch.org you can use https://fosstorrents.com/distributions/black-arch/

**Comment by noraj** [comment]
Should be good now.
