### ISSUE TITLE
Tools list

### ISSUE THREAD

**Issue by Anyon3** [BlackArch/blackarch-site#50]
pulsar - generate an incorrect href (https://blackarch.org/Protocol%20Learning%20and%20Stateful%20Fuzzing.)

vnc-bypauth 

> Bad character = after <. Probable cause: Unescaped <. Try escaping it as &lt; 

add a space between <= (like this : < =) for avoid this "error" of the standard w3c

When those 2 small fix will be add, the page tools.html will not fail any more

**Comment by noptrix** [comment]
thanks a lot. fixed
