### ISSUE TITLE
Create Automatic Mirror Redirection System for ISOs

### ISSUE THREAD

**Issue by ghost** [BlackArch/blackarch-site#60]
Large files targeting a single mirror seem to bring that mirror to it's knees when a new ISO is released. This was witnessed when a new ISO release was done a few days ago. The blackarch.org site got slowed to a crawl and saw less than 1MB/s download times. 

Most major distributions use a round-robin or closest-mirror system to direct an individual automatically to the mirror closest to them. Implementing that will reduce stress on the master blackarch.org site and mirror.

**Comment by Anyon3** [comment]
Agree, I will see what we can do about it

Thanks for the report
