### ISSUE TITLE
I want to contribute in the website design..

### ISSUE THREAD

**Issue by parasharrajat** [BlackArch/blackarch-site#78]
Hello ,
      I am Rajat Parashar. I want permission for contributing in Blackarch Website Source but my approach is different, I want to use React and other modern tools for this while sticking to your shell scripting so that you will be able to deploy with no server side change. 
  I am new to github and FOSS contribution that's why I want to exercise my skills.
Thanks in advance ! happy H/\<KinG ><

**Comment by PedroSFreitas** [comment]
@parasharrajat, thanks, we appreciate it. But for security reasons, the website should stay as static as possible.
