### ISSUE TITLE
Migrate to jekyll

### ISSUE THREAD

**Issue by milovanderlinden** [BlackArch/blackarch-site#87]
I would like to volunteer to migrate the site to jekyll (github pages). That way you would only need a CNAME pointing to this repository and the site will automagically be hosted here. The reason I am asking is because I have experience with that and because I noticed the mobile version of the site is not working correct (navbar burger is not unfolding). Besides that I noticed that the ./generate-site.sh script will not reflect changes I make unless I delete all the html files the whole time.

Would you guys like me to do that?

**Comment by milovanderlinden** [comment]
I have done the first batch of migration. You can see it here: https://milovanderlinden.github.io/blackarch-site/ code at https://github.com/milovanderlinden/blackarch-site

**Comment by PedroSFreitas** [comment]
@milovanderlinden thanks a bunch for your work

@noptrix any interest? If not, we should consider closing this Issue.

**Comment by milovanderlinden** [comment]
The site can be reached at https://www.blackarch.io if you like it, you can use it and I also offered the domain to @noptrix. It has the jekyll version active.

**Comment by PedroSFreitas** [comment]
@milovanderlinden I do like it!
Can we also have a wiki like that?

@noptrix What do you think? I think it's clean, modern, flat. I liked it.

Also I loved the Packages page.

**Comment by milovanderlinden** [comment]
Thank you for the kind words @PedroSFreitas. Regarding the wiki; that would be possible by using a jekyll plugin https://github.com/djacquel/WikiToJekyll but as with the packages, we would need to trigger it manually from time to time.

**Comment by noptrix** [comment]
Hey guys. Sorry, I totally missed this issue... @milovanderlinden this rocks really. But can we get a 'darker' version of this? Mix of black, grey, white, red ... Would that be possible?

**Comment by milovanderlinden** [comment]
Of course! Gladly facilitate.

**Comment by milovanderlinden** [comment]
Ok, I set up a dark version at http://www.blackarch.io please let me know if you like it.

**Comment by noptrix** [comment]
@milovanderlinden Wow, this looks really nice. The only little thing I personally see is the font. For example: https://www.blackarch.io/faq.html looks a bit confusing in the first glance. Do you think a different font could help us here? All in all, it's near to our expectations and I could really think of to replace the current complicated site with yours. :)

**Comment by noptrix** [comment]
> @milovanderlinden Wow, this looks really nice. The only little thing I personally see is the font. For example: https://www.blackarch.io/faq.html looks a bit confusing in the first glance. Do you think a different font could help us here? All in all, it's near to our expectations and I could really think of to replace the current complicated site with yours. :)

Whereby, I think it's not the font. Maybe we shoul use red colored subjects in faq.html, because the other pages look good. 

@milovanderlinden Let me talk to few ppl and then get back to you. I personally would replace current site with yours. It looks really clean. Can you just tell me what we would have to do in order to update website when for example generating up-to-date package list or make a blog entry or whatever? Is it easy? also, https://www.blackarch.io/iso/2018/12/01/iso-released.html is still in white. but i think that's just an example right?

If possible, let's meet on IRC/Jabber/Discord/whatever to discuss this. We would really like to replace our website with yours.

**Comment by milovanderlinden** [comment]
I have changed the titles on the faq page to red and did some other changes as well. I am not on discord, but I joined the irc channel today.

**Comment by ikstream** [comment]
@noptrix This looks still pretty good to me and could be integrated with some CI to update automatically on pushes to the site repo. 
Are you still interested in it?

**Comment by ikstream** [comment]
Hi @milovanderlinden unfortunately this didn't get moived forward anymore. 
Would you be so kind and take blackarch.io offline, as it causes some confusion every now and than.

**Comment by noptrix** [comment]
@milovanderlinden please take blackarch.io down.
