### ISSUE TITLE
change dd install example for n00bs

### ISSUE THREAD

**Issue by debragail** [BlackArch/blackarch-site#92]
Current:

`$ sudo dd bs=512M if=file.iso of=/dev/sdX`

Expected:

`$ sudo dd bs=512 if=file.iso of=/dev/sdX`

<img width="913" alt="screen shot 2018-05-27 at 06 09 23" src="https://user-images.githubusercontent.com/552529/40586252-db28889a-6174-11e8-9ea9-aa107933b9a4.png">

**Comment by debragail** [comment]
Also `bs=512` takes forever I recommend:

`bs=1048576`

**Comment by ikstream** [comment]
On Mac you have to use ```512m``` instead of ```512M``` i think to make it work.

**Comment by debragail** [comment]
Macs have case sensitive journaling but I’m suggesting a faster block size

**Comment by ikstream** [comment]
Based on my understanding of the man page of dd ```bs=512``` would mean blocksize of 512 bytes, ```bs=1048576``` would be somewhere around 1MB, ```bs=512M``` would mean a blocksize of 512MB. 
so there schould be a big difference between ```bs=512``` and ```bs=512M```
Imo 512M is to big and should be somewhere around 512k(which still takes a long while), but optimal write speed depends on your hardware

**Comment by noptrix** [comment]
thanks guys. i am closing this here.
